# Generated by Django 5.0.6 on 2024-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='agreed_to_terms',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c0f520', max_length=6),
        ),
    ]
