# Generated by Django 5.0.6 on 2024-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecapital',
            name='payement_date',
        ),
        migrations.RemoveField(
            model_name='sharecapitalpartialpayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscriptionpartialpayment',
            name='date',
        ),
        migrations.AddField(
            model_name='sharecapital',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sharecapitalpartialpayment',
            name='partial_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpartialpayment',
            name='partial_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='78f0a5', max_length=6),
        ),
    ]
