# Generated by Django 5.0.6 on 2024-07-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('outstanding', 'Outstanding'), ('cleared', 'Cleared')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='application_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanstatus',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_application_status', to='coop.loanapplication'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='6003fa', max_length=6),
        ),
    ]
