# Generated by Django 5.0.6 on 2024-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_alter_sharecapital_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecapitall',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
