# Generated by Django 5.0.6 on 2024-07-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_remove_sharecapital_payement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='4a06da', max_length=6),
        ),
    ]
