# Generated by Django 5.0.6 on 2024-08-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coop', '0004_rename_customuser_member_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='bbdb74', max_length=6),
        ),
    ]
