# Generated by Django 5.0.6 on 2024-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0006_customuser_is_member_customuser_membership_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5885ee', max_length=6),
        ),
    ]
