# Generated by Django 5.0.6 on 2024-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='3309ec', max_length=6),
        ),
    ]
